[package]
name = "jsonrepair-rs-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde = "1"
serde_json = { version = "1", features = ["arbitrary_precision", "unbounded_depth"] }

[dependencies.jsonrepair-rs]
path = ".."

[[bin]]
name = "repair_parser"
path = "fuzz_targets/repair_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "repair_stream"
path = "fuzz_targets/repair_stream.rs"
test = false
doc = false
bench = false
